### ISSUE TITLE
Just spawned in penguins and they're invincible?

### ISSUE THREAD

**Issue by CODEGOAT007** [arkutils/arkutils-website#2]
Just spawned in penguins and they're invincible? Trying to spawn in 2 dinos that are EXACTLY the same to do controlled tests.

**Comment by TiiaAurora** [comment]
How often did you cryo them after the spawning?  

At the bottom of the generator it says: 

Warning:
Creatures spawned with this method are broken until cryo'd.
Maybe even twice. You have been warned!

**Comment by TiiaAurora** [comment]
Tested and creatures work normal after being cryo'ed.
