### ISSUE TITLE
Spawn Exact Dino Doesn't Take Letters for "Imprinter's Ark ID"

### ISSUE THREAD

**Issue by DrDopeness** [arkutils/arkutils-website#4]
In ASA they have switched from using the unique player ID generated in game to the EpicID. The EpicID is a string that contains 32 characters made up of digits (0-9) and letters (a-f). Based on what I have seen.

The Imprinter's Ark ID seems to take numbers for forever but as soon as a letter is put in there it removes it from the generated command. 

It really should be limited to 32 characters and allow user input to be digits (0-9) and letters (a-f).

**Comment by DrDopeness** [comment]
Update src/routes/(pages)/tools/spawnexact/+page.svelte
//Line 17
let imprintID: string = ''; // Change to string to allow hex input

// Add after line 19 to Ensure valid hex input and limit up to 32 characters
function handleImprintIDInput(event: Event) {
	const input = (event.target as HTMLInputElement).value;
	imprintID = input.replace(/[^0-9a-fA-F]/g, '').slice(0, 32);

**Comment by coldino** [comment]
Thanks! Didn't realise this was an issue. Fixed it almost as you suggested, just slightly more Svelte-like: 30efb137e5d3d23aafd28fb470df4a76006a8963

This change just went live along with a new Reaper Baby Calculator and a few small global tweaks.
